{
 "title": "dSolar Power (example)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "All Power",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(mppt_power)", "legendFormat": "PV" },
    { "expr": "sum(load_power)", "legendFormat": "LOAD" }
   ]
  },
  {
   "title": "All Power",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 17, "x": 7, "y": 0 },
   "targets": [
    { "expr": "sum(mppt_power)", "legendFormat": "PV" },
    { "expr": "sum(bat_power)", "legendFormat": "Battery" },
    { "expr": "sum(load_power)", "legendFormat": "Load" },
    { "expr": "sum(grid_power)", "legendFormat": "Grid" }
   ]
  },
  {
   "title": "All Power",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(bat_power)", "legendFormat": "BATTERY" },
    { "expr": "sum(grid_power)", "legendFormat": "GRID" }
   ]
  },
  {
   "title": "PV",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "mppt_power", "legendFormat": "{{device}} {{mppt}}" },
    { "expr": "sum by(device) (mppt_power)", "legendFormat": "{{device}}" }
   ]
  },
  {
   "title": "PV",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mppt_power", "legendFormat": "{{device}} {{mppt}}" },
    { "expr": "sum by(device) (mppt_power)", "legendFormat": "{{device}}" }
   ]
  },
  {
   "title": "LOAD",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "sum by(device) (load_power)", "legendFormat": "{{device}}" }
   ]
  },
  {
   "title": "BATTERY",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "sum by(device) (bat_power)", "legendFormat": "{{device}}" }
   ]
  },
  {
   "title": "GRID",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "sum by(device) (grid_power)", "legendFormat": "{{device}}" }
   ]
  },
  {
   "title": "LOAD",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum by(device) (load_power)", "legendFormat": "{{device}}" }
   ]
  },
  {
   "title": "BATTERY",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum by(device) (bat_power)", "legendFormat": "{{device}}" }
   ]
  },
  {
   "title": "GRID",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum by(device) (grid_power)", "legendFormat": "{{device}}" }
   ]
  }
 ]
}